from app.models.pokemon_relation import PokemonRelation
from pokemendel_core.data.gen1 import PokemonGen1

# Maps each marked pokemon to a PokemonRelation describing starter preference.
# Types reference the starter types defined in config.yaml (grass, fire, water).
# Fill in the relations for each pokemon.

STARTER_MAPPING: dict[str, PokemonRelation] = {
    PokemonGen1.ABRA: PokemonRelation(want={"grass"}),
    PokemonGen1.AERODACTYL: PokemonRelation(really_want={"fire"}, want={"grass"}, dont_want={"water"}),
    PokemonGen1.ARTICUNO: PokemonRelation(really_want={"grass"}, dont_want={"fire"}),
    PokemonGen1.BELLSPROUT: PokemonRelation(want={"water"}, dont_want={"fire"}),
    PokemonGen1.CATERPIE: PokemonRelation(really_want={"grass"}, dont_want={"fire"}),
    PokemonGen1.CHANSEY: PokemonRelation(),
    PokemonGen1.CLEFAIRY: PokemonRelation(),
    PokemonGen1.DIGLETT: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen1.DITTO: PokemonRelation(),
    PokemonGen1.DODUO: PokemonRelation(want={"grass"}),
    PokemonGen1.DRATINI: PokemonRelation(),
    PokemonGen1.DROWZEE: PokemonRelation(want={"grass"}),
    PokemonGen1.EEVEE: PokemonRelation(),
    PokemonGen1.EKANS: PokemonRelation(want={"grass"}),
    PokemonGen1.ELECTABUZZ: PokemonRelation(want={"water", "fire"}, dont_want={"grass"}),
    PokemonGen1.EXEGGCUTE: PokemonRelation(want={"water", "grass"}, dont_want={"fire"}),
    PokemonGen1.FARFETCHD: PokemonRelation(want={"grass"}),
    PokemonGen1.FLAREON: PokemonRelation(dont_want={"water", "fire"}, want={"grass"}),
    PokemonGen1.GASTLY: PokemonRelation(want={"grass"}),
    PokemonGen1.GEODUDE: PokemonRelation(really_want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen1.GOLDEEN: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen1.GRIMER: PokemonRelation(want={"grass"}),
    PokemonGen1.GROWLITHE: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen1.HITMONCHAN: PokemonRelation(dont_want={"fire"}),
    PokemonGen1.HITMONLEE: PokemonRelation(dont_want={"fire"}),
    PokemonGen1.HORSEA: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen1.JIGGLYPUFF: PokemonRelation(),
    PokemonGen1.JOLTEON: PokemonRelation(want={"water", "fire"}, dont_want={"grass"}),
    PokemonGen1.JYNX: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen1.KABUTO: PokemonRelation(want={"fire"}, dont_want={"green"}),
    PokemonGen1.KANGASKHAN: PokemonRelation(),
    PokemonGen1.KOFFING: PokemonRelation(want={"grass"}),
    PokemonGen1.KRABBY: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen1.LAPRAS: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen1.LICKITUNG: PokemonRelation(),
    PokemonGen1.MACHOP: PokemonRelation(dont_want={"fire", "grass"}),
    PokemonGen1.MAGIKARP: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen1.MAGMAR: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen1.MAGNEMITE: PokemonRelation(want={"water", "fire"}, dont_want={"grass"}),
    PokemonGen1.MANKEY: PokemonRelation(dont_want={"fire"}),
    PokemonGen1.MEOWTH: PokemonRelation(),
    PokemonGen1.MEW: PokemonRelation(want={"grass"}),
    PokemonGen1.MEWTWO: PokemonRelation(want={"grass"}),
    PokemonGen1.MOLTRES: PokemonRelation(want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen1.MR_MIME: PokemonRelation(want={"grass"}),
    PokemonGen1.NIDORAN_F: PokemonRelation(dont_want={"water"}, want={"grass"}),
    PokemonGen1.NIDORAN_M: PokemonRelation(dont_want={"water"}, want={"grass"}),
    PokemonGen1.ODDISH: PokemonRelation(want={"water"}, dont_want={"fire"}),
    PokemonGen1.OMANYTE: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen1.ONIX: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen1.PARAS: PokemonRelation(want={"grass", "water"}, dont_want={"fire"}),
    PokemonGen1.PIDGEY: PokemonRelation(want={"grass"}),
    PokemonGen1.PIKACHU: PokemonRelation(want={"water", "fire"}, dont_want={"grass"}),
    PokemonGen1.PINSIR: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen1.POLIWAG: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen1.PONYTA: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen1.PORYGON: PokemonRelation(),
    PokemonGen1.PSYDUCK: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen1.RATTATA: PokemonRelation(),
    PokemonGen1.RHYHORN: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen1.SANDSHREW: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen1.SCYTHER: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen1.SEEL: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen1.SHELLDER: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen1.SLOWPOKE: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen1.SNORLAX: PokemonRelation(),
    PokemonGen1.SPEAROW: PokemonRelation(want={"grass"}),
    PokemonGen1.STARYU: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen1.TANGELA: PokemonRelation(want={"water"}, dont_want={"fire", "grass"}),
    PokemonGen1.TAUROS: PokemonRelation(),
    PokemonGen1.TENTACOOL: PokemonRelation(want={"fire"}),
    PokemonGen1.VAPOREON: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen1.VENONAT: PokemonRelation(dont_want={"fire"}),
    PokemonGen1.VOLTORB: PokemonRelation(want={"water", "fire"}, dont_want={"grass"}),
    PokemonGen1.VULPIX: PokemonRelation(want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen1.WEEDLE: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen1.ZAPDOS: PokemonRelation(want={"fire", "grass", "water"}),
}
