from app.models.pokemon_relation import PokemonRelation
from pokemendel_core.data.gen4 import PokemonGen4


STARTER_MAPPING: dict[str, PokemonRelation] = {
    PokemonGen4.ABRA: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.ABSOL: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.AERODACTYL: PokemonRelation(want={'fire', 'grass'}, dont_want={'water'}),
    PokemonGen4.AIPOM: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.ANORITH: PokemonRelation(dont_want={'water'}),
    PokemonGen4.ARCEUS: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.ARON: PokemonRelation(dont_want={'water', 'fire', 'grass'}),
    PokemonGen4.ARTICUNO: PokemonRelation(really_want={'grass'}, dont_want={'water'}),
    PokemonGen4.AZELF: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.AZURILL: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.BAGON: PokemonRelation(want={'fire', 'grass'}, dont_want={'water'}),
    PokemonGen4.BALTOY: PokemonRelation(want={'fire'}, dont_want={'grass'}),
    PokemonGen4.BARBOACH: PokemonRelation(want={'water', 'fire'}, dont_want={'grass'}),
    PokemonGen4.BELDUM: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.BELLOSSOM: PokemonRelation(dont_want={'fire'}),
    PokemonGen4.BELLSPROUT: PokemonRelation(dont_want={'fire'}),
    PokemonGen4.BIDOOF: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.BONSLY: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.BRONZOR: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.BUDEW: PokemonRelation(dont_want={'fire'}),
    PokemonGen4.BUIZEL: PokemonRelation(want={'fire'}, dont_want={'grass'}),
    PokemonGen4.BULBASAUR: PokemonRelation(dont_want={'fire'}),
    PokemonGen4.BUNEARY: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.CACNEA: PokemonRelation(want={'grass'}, dont_want={'fire'}),
    PokemonGen4.CARNIVINE: PokemonRelation(dont_want={'fire'}),
    PokemonGen4.CARVANHA: PokemonRelation(),
    PokemonGen4.CASCOON: PokemonRelation(want={'grass'}, dont_want={'fire'}),
    PokemonGen4.CASTFORM: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.CATERPIE: PokemonRelation(want={'grass'}, dont_want={'water'}),
    PokemonGen4.CELEBI: PokemonRelation(want={'grass'}),
    PokemonGen4.CHARMANDER: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.CHATOT: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.CHERUBI: PokemonRelation(dont_want={'fire'}),
    PokemonGen4.CHIKORITA: PokemonRelation(dont_want={'fire'}),
    PokemonGen4.CHIMCHAR: PokemonRelation(),
    PokemonGen4.CHINCHOU: PokemonRelation(want={'water', 'fire'}, dont_want={'grass'}),
    PokemonGen4.CHINGLING: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.CLEFFA: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.COMBEE: PokemonRelation(really_want={'grass'}, dont_want={'water'}),
    PokemonGen4.CORPHISH: PokemonRelation(dont_want={'grass'}),
    PokemonGen4.CORSOLA: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.CRANIDOS: PokemonRelation(dont_want={'water', 'fire', 'grass'}),
    PokemonGen4.CRESSELIA: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.CROAGUNK: PokemonRelation(want={'water'}, dont_want={'grass'}),
    PokemonGen4.CUBONE: PokemonRelation(want={'fire'}, dont_want={'grass'}),
    PokemonGen4.CYNDAQUIL: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.DARKRAI: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.DELCATTY: PokemonRelation(),
    PokemonGen4.DELIBIRD: PokemonRelation(really_want={'grass'}, dont_want={'water'}),
    PokemonGen4.DEOXYS: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.DEWGONG: PokemonRelation(),
    PokemonGen4.DIALGA: PokemonRelation(dont_want={'fire'}),
    PokemonGen4.DIGLETT: PokemonRelation(want={'fire'}, dont_want={'grass'}),
    PokemonGen4.DITTO: PokemonRelation(),
    PokemonGen4.DODRIO: PokemonRelation(),
    PokemonGen4.DODUO: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.DONPHAN: PokemonRelation(),
    PokemonGen4.DRAGONAIR: PokemonRelation(),
    PokemonGen4.DRAGONITE: PokemonRelation(),
    PokemonGen4.DRAPION: PokemonRelation(),
    PokemonGen4.DRATINI: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.DRIFBLIM: PokemonRelation(),
    PokemonGen4.DRIFLOON: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.DROWZEE: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.DUGTRIO: PokemonRelation(),
    PokemonGen4.DUNSPARCE: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.DUSCLOPS: PokemonRelation(),
    PokemonGen4.DUSKNOIR: PokemonRelation(),
    PokemonGen4.DUSKULL: PokemonRelation(dont_want={'water'}),
    PokemonGen4.DUSTOX: PokemonRelation(),
    PokemonGen4.EEVEE: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.EKANS: PokemonRelation(dont_want={'grass'}, no_way_jose={'water'}),
    PokemonGen4.ELECTABUZZ: PokemonRelation(),
    PokemonGen4.ELECTIVIRE: PokemonRelation(),
    PokemonGen4.ELECTRIKE: PokemonRelation(want={'water'}, no_way_jose={'grass'}),
    PokemonGen4.ELECTRODE: PokemonRelation(),
    PokemonGen4.ELEKID: PokemonRelation(want={'water'}, no_way_jose={'grass'}),
    PokemonGen4.EMPOLEON: PokemonRelation(),
    PokemonGen4.ENTEI: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.ESPEON: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.EXEGGCUTE: PokemonRelation(want={'grass'}),
    PokemonGen4.EXEGGUTOR: PokemonRelation(),
    PokemonGen4.EXPLOUD: PokemonRelation(),
    PokemonGen4.FAN_ROTOM: PokemonRelation(really_want={'grass'}, want={'water', 'fire'}),
    PokemonGen4.FARFETCHD: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.FEAROW: PokemonRelation(),
    PokemonGen4.FEEBAS: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.FERALIGATR: PokemonRelation(),
    PokemonGen4.FINNEON: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.FLAAFFY: PokemonRelation(),
    PokemonGen4.FLAREON: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.FLOATZEL: PokemonRelation(),
    PokemonGen4.FLYGON: PokemonRelation(),
    PokemonGen4.FORRETRESS: PokemonRelation(),
    PokemonGen4.FROSLASS: PokemonRelation(really_want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.FROST_ROTOM: PokemonRelation(really_want={'grass'}, want={'water'}, dont_want={'fire'}),
    PokemonGen4.FURRET: PokemonRelation(),
    PokemonGen4.GABITE: PokemonRelation(),
    PokemonGen4.GALLADE: PokemonRelation(want={'water', 'fire'}),
    PokemonGen4.GARCHOMP: PokemonRelation(),
    PokemonGen4.GARDEVOIR: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.GASTLY: PokemonRelation(dont_want={'water'}),
    PokemonGen4.GASTRODON: PokemonRelation(),
    PokemonGen4.GENGAR: PokemonRelation(),
    PokemonGen4.GEODUDE: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.GIBLE: PokemonRelation(want={'water', 'fire'}),
    PokemonGen4.GIRAFARIG: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.GIRATINA: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.GIRATINA_ORIGIN: PokemonRelation(),
    PokemonGen4.GLACEON: PokemonRelation(want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.GLALIE: PokemonRelation(want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.GLAMEOW: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.GLIGAR: PokemonRelation(want={'fire', 'grass'}),
    PokemonGen4.GLISCOR: PokemonRelation(),
    PokemonGen4.GLOOM: PokemonRelation(),
    PokemonGen4.GOLBAT: PokemonRelation(),
    PokemonGen4.GOLDEEN: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.GOLDUCK: PokemonRelation(),
    PokemonGen4.GOLEM: PokemonRelation(),
    PokemonGen4.GOREBYSS: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.GRANBULL: PokemonRelation(),
    PokemonGen4.GRAVELER: PokemonRelation(),
    PokemonGen4.GRIMER: PokemonRelation(dont_want={'grass'}, no_way_jose={'water'}),
    PokemonGen4.GROTLE: PokemonRelation(),
    PokemonGen4.GROUDON: PokemonRelation(want={'fire'}, dont_want={'grass'}),
    PokemonGen4.GROVYLE: PokemonRelation(),
    PokemonGen4.GROWLITHE: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.GRUMPIG: PokemonRelation(),
    PokemonGen4.GULPIN: PokemonRelation(dont_want={'grass'}, no_way_jose={'water'}),
    PokemonGen4.GYARADOS: PokemonRelation(),
    PokemonGen4.HAPPINY: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.HARIYAMA: PokemonRelation(),
    PokemonGen4.HAUNTER: PokemonRelation(),
    PokemonGen4.HEAT_ROTOM: PokemonRelation(),
    PokemonGen4.HEATRAN: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.HERACROSS: PokemonRelation(really_want={'grass'}, want={'water'}, dont_want={'fire'}),
    PokemonGen4.HIPPOPOTAS: PokemonRelation(want={'fire'}, dont_want={'grass'}),
    PokemonGen4.HIPPOWDON: PokemonRelation(),
    PokemonGen4.HITMONCHAN: PokemonRelation(want={'water'}),
    PokemonGen4.HITMONLEE: PokemonRelation(want={'water'}),
    PokemonGen4.HITMONTOP: PokemonRelation(want={'water'}),
    PokemonGen4.HO_OH: PokemonRelation(really_want={'fire', 'grass'}, dont_want={'water'}),
    PokemonGen4.HONCHKROW: PokemonRelation(),
    PokemonGen4.HOOTHOOT: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.HOPPIP: PokemonRelation(really_want={'grass'}),
    PokemonGen4.HORSEA: PokemonRelation(want={'fire'}),
    PokemonGen4.HOUNDOOM: PokemonRelation(),
    PokemonGen4.HOUNDOUR: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.HUNTAIL: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.HYPNO: PokemonRelation(),
    PokemonGen4.IGGLYBUFF: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.ILLUMISE: PokemonRelation(really_want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.INFERNAPE: PokemonRelation(),
    PokemonGen4.IVYSAUR: PokemonRelation(),
    PokemonGen4.JIGGLYPUFF: PokemonRelation(),
    PokemonGen4.JIRACHI: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.JOLTEON: PokemonRelation(want={'water'}, no_way_jose={'grass'}),
    PokemonGen4.JUMPLUFF: PokemonRelation(),
    PokemonGen4.JYNX: PokemonRelation(),
    PokemonGen4.KABUTO: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.KABUTOPS: PokemonRelation(),
    PokemonGen4.KADABRA: PokemonRelation(),
    PokemonGen4.KAKUNA: PokemonRelation(),
    PokemonGen4.KANGASKHAN: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.KECLEON: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.KINGDRA: PokemonRelation(),
    PokemonGen4.KINGLER: PokemonRelation(),
    PokemonGen4.KIRLIA: PokemonRelation(),
    PokemonGen4.KOFFING: PokemonRelation(dont_want={'grass'}, no_way_jose={'water'}),
    PokemonGen4.KRABBY: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.KRICKETOT: PokemonRelation(want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.KRICKETUNE: PokemonRelation(),
    PokemonGen4.KYOGRE: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.LAIRON: PokemonRelation(),
    PokemonGen4.LANTURN: PokemonRelation(),
    PokemonGen4.LAPRAS: PokemonRelation(dont_want={'water'}),
    PokemonGen4.LARVITAR: PokemonRelation(dont_want={'water', 'fire', 'grass'}),
    PokemonGen4.LATIAS: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.LATIOS: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.LEAFEON: PokemonRelation(want={'grass'}, dont_want={'fire'}),
    PokemonGen4.LEDIAN: PokemonRelation(),
    PokemonGen4.LEDYBA: PokemonRelation(really_want={'grass'}, dont_want={'water'}),
    PokemonGen4.LICKILICKY: PokemonRelation(),
    PokemonGen4.LICKITUNG: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.LILEEP: PokemonRelation(dont_want={'fire', 'grass'}),
    PokemonGen4.LINOONE: PokemonRelation(),
    PokemonGen4.LOMBRE: PokemonRelation(),
    PokemonGen4.LOPUNNY: PokemonRelation(),
    PokemonGen4.LOTAD: PokemonRelation(want={'fire'}),
    PokemonGen4.LOUDRED: PokemonRelation(),
    PokemonGen4.LUCARIO: PokemonRelation(),
    PokemonGen4.LUDICOLO: PokemonRelation(),
    PokemonGen4.LUGIA: PokemonRelation(really_want={'fire', 'grass'}, dont_want={'water'}),
    PokemonGen4.LUMINEON: PokemonRelation(),
    PokemonGen4.LUNATONE: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.LUVDISC: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.LUXIO: PokemonRelation(),
    PokemonGen4.LUXRAY: PokemonRelation(),
    PokemonGen4.MACHAMP: PokemonRelation(),
    PokemonGen4.MACHOKE: PokemonRelation(),
    PokemonGen4.MACHOP: PokemonRelation(want={'water'}),
    PokemonGen4.MAGBY: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.MAGCARGO: PokemonRelation(),
    PokemonGen4.MAGIKARP: PokemonRelation(really_want={'fire'}, want={'grass'}),
    PokemonGen4.MAGMAR: PokemonRelation(),
    PokemonGen4.MAGMORTAR: PokemonRelation(),
    PokemonGen4.MAGNEMITE: PokemonRelation(want={'water'}, dont_want={'fire'}, no_way_jose={'grass'}),
    PokemonGen4.MAGNETON: PokemonRelation(),
    PokemonGen4.MAGNEZONE: PokemonRelation(),
    PokemonGen4.MAKUHITA: PokemonRelation(want={'water'}),
    PokemonGen4.MAMOSWINE: PokemonRelation(),
    PokemonGen4.MANAPHY: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.MANECTRIC: PokemonRelation(),
    PokemonGen4.MANKEY: PokemonRelation(want={'water'}),
    PokemonGen4.MANTINE: PokemonRelation(),
    PokemonGen4.MANTYKE: PokemonRelation(really_want={'fire'}, want={'grass'}, dont_want={'water'}),
    PokemonGen4.MAREEP: PokemonRelation(want={'water'}, no_way_jose={'grass'}),
    PokemonGen4.MARILL: PokemonRelation(),
    PokemonGen4.MAROWAK: PokemonRelation(),
    PokemonGen4.MARSHTOMP: PokemonRelation(),
    PokemonGen4.MASQUERAIN: PokemonRelation(),
    PokemonGen4.MAWILE: PokemonRelation(dont_want={'water', 'fire', 'grass'}),
    PokemonGen4.MEDICHAM: PokemonRelation(),
    PokemonGen4.MEDITITE: PokemonRelation(want={'water', 'fire'}),
    PokemonGen4.MEGANIUM: PokemonRelation(),
    PokemonGen4.MEOWTH: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.MESPRIT: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.METAGROSS: PokemonRelation(),
    PokemonGen4.METANG: PokemonRelation(),
    PokemonGen4.METAPOD: PokemonRelation(),
    PokemonGen4.MEW: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.MEWTWO: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.MIGHTYENA: PokemonRelation(),
    PokemonGen4.MILOTIC: PokemonRelation(),
    PokemonGen4.MILTANK: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.MIME_JR: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.MINUN: PokemonRelation(want={'water'}, no_way_jose={'grass'}),
    PokemonGen4.MISDREAVUS: PokemonRelation(dont_want={'water'}),
    PokemonGen4.MISMAGIUS: PokemonRelation(),
    PokemonGen4.MOLTRES: PokemonRelation(really_want={'fire', 'grass'}, dont_want={'water'}),
    PokemonGen4.MONFERNO: PokemonRelation(),
    PokemonGen4.MOTHIM: PokemonRelation(really_want={'grass'}, dont_want={'water'}),
    PokemonGen4.MOW_ROTOM: PokemonRelation(want={'water'}, dont_want={'fire', 'grass'}),
    PokemonGen4.MR_MIME: PokemonRelation(),
    PokemonGen4.MUDKIP: PokemonRelation(want={'water', 'fire'}, dont_want={'grass'}),
    PokemonGen4.MUK: PokemonRelation(),
    PokemonGen4.MUNCHLAX: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.MURKROW: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.NATU: PokemonRelation(really_want={'fire', 'grass'}, dont_want={'water'}),
    PokemonGen4.NIDOKING: PokemonRelation(),
    PokemonGen4.NIDOQUEEN: PokemonRelation(),
    PokemonGen4.NIDORAN_F: PokemonRelation(want={'fire'}, dont_want={'grass'}),
    PokemonGen4.NIDORAN_M: PokemonRelation(want={'fire'}, dont_want={'grass'}),
    PokemonGen4.NIDORINA: PokemonRelation(),
    PokemonGen4.NIDORINO: PokemonRelation(),
    PokemonGen4.NINCADA: PokemonRelation(),
    PokemonGen4.NINETALES: PokemonRelation(),
    PokemonGen4.NINJASK: PokemonRelation(really_want={'grass'}, dont_want={'water'}),
    PokemonGen4.NOCTOWL: PokemonRelation(),
    PokemonGen4.NOSEPASS: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.NUMEL: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.NUZLEAF: PokemonRelation(),
    PokemonGen4.OCTILLERY: PokemonRelation(),
    PokemonGen4.ODDISH: PokemonRelation(),
    PokemonGen4.OMANYTE: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.OMASTAR: PokemonRelation(),
    PokemonGen4.ONIX: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.PACHIRISU: PokemonRelation(want={'water'}, no_way_jose={'grass'}),
    PokemonGen4.PALKIA: PokemonRelation(want={'fire'}),
    PokemonGen4.PARAS: PokemonRelation(want={'grass'}, dont_want={'fire'}),
    PokemonGen4.PARASECT: PokemonRelation(),
    PokemonGen4.PELIPPER: PokemonRelation(),
    PokemonGen4.PERSIAN: PokemonRelation(),
    PokemonGen4.PHANPY: PokemonRelation(want={'fire'}, dont_want={'grass'}),
    PokemonGen4.PHIONE: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.PICHU: PokemonRelation(want={'water'}, no_way_jose={'grass'}),
    PokemonGen4.PIDGEOT: PokemonRelation(),
    PokemonGen4.PIDGEOTTO: PokemonRelation(),
    PokemonGen4.PIDGEY: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.PIKACHU: PokemonRelation(),
    PokemonGen4.PILOSWINE: PokemonRelation(),
    PokemonGen4.PINECO: PokemonRelation(really_want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.PINSIR: PokemonRelation(really_want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.PIPLUP: PokemonRelation(),
    PokemonGen4.PLUSLE: PokemonRelation(want={'water'}, no_way_jose={'grass'}),
    PokemonGen4.POLITOED: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.POLIWAG: PokemonRelation(),
    PokemonGen4.POLIWHIRL: PokemonRelation(),
    PokemonGen4.POLIWRATH: PokemonRelation(want={'water', 'fire'}, dont_want={'grass'}),
    PokemonGen4.PONYTA: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.POOCHYENA: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.PORYGON: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.PORYGON_Z: PokemonRelation(),
    PokemonGen4.PORYGON2: PokemonRelation(),
    PokemonGen4.PRIMEAPE: PokemonRelation(),
    PokemonGen4.PRINPLUP: PokemonRelation(),
    PokemonGen4.PROBOPASS: PokemonRelation(),
    PokemonGen4.PSYDUCK: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.PUPITAR: PokemonRelation(),
    PokemonGen4.PURUGLY: PokemonRelation(),
    PokemonGen4.QUAGSIRE: PokemonRelation(),
    PokemonGen4.QUILAVA: PokemonRelation(),
    PokemonGen4.QWILFISH: PokemonRelation(really_want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.RAICHU: PokemonRelation(),
    PokemonGen4.RAIKOU: PokemonRelation(want={'water'}, no_way_jose={'grass'}),
    PokemonGen4.RALTS: PokemonRelation(),
    PokemonGen4.RAMPARDOS: PokemonRelation(),
    PokemonGen4.RAPIDASH: PokemonRelation(),
    PokemonGen4.RATICATE: PokemonRelation(),
    PokemonGen4.RATTATA: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.RAYQUAZA: PokemonRelation(really_want={'fire', 'grass'}, want={'water'}),
    PokemonGen4.REGICE: PokemonRelation(want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.REGIGIGAS: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.REGIROCK: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.REGISTEEL: PokemonRelation(dont_want={'water', 'fire', 'grass'}),
    PokemonGen4.RELICANTH: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.REMORAID: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.RHYDON: PokemonRelation(),
    PokemonGen4.RHYHORN: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.RHYPERIOR: PokemonRelation(),
    PokemonGen4.RIOLU: PokemonRelation(want={'water'}, dont_want={'fire', 'grass'}),
    PokemonGen4.ROSELIA: PokemonRelation(),
    PokemonGen4.ROSERADE: PokemonRelation(),
    PokemonGen4.ROTOM: PokemonRelation(want={'water'}),
    PokemonGen4.SABLEYE: PokemonRelation(dont_want={'water'}),
    PokemonGen4.SALAMENCE: PokemonRelation(),
    PokemonGen4.SANDSHREW: PokemonRelation(want={'fire'}, dont_want={'grass'}),
    PokemonGen4.SANDSLASH: PokemonRelation(),
    PokemonGen4.SCEPTILE: PokemonRelation(),
    PokemonGen4.SCIZOR: PokemonRelation(),
    PokemonGen4.SCYTHER: PokemonRelation(want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.SEADRA: PokemonRelation(),
    PokemonGen4.SEAKING: PokemonRelation(),
    PokemonGen4.SEALEO: PokemonRelation(),
    PokemonGen4.SEEDOT: PokemonRelation(want={'grass'}, dont_want={'fire'}),
    PokemonGen4.SEEL: PokemonRelation(dont_want={'water'}),
    PokemonGen4.SENTRET: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.SEVIPER: PokemonRelation(dont_want={'grass'}, no_way_jose={'water'}),
    PokemonGen4.SHARPEDO: PokemonRelation(),
    PokemonGen4.SHAYMIN_LAND: PokemonRelation(want={'grass'}, dont_want={'fire'}),
    PokemonGen4.SHAYMIN_SKY: PokemonRelation(really_want={'grass'}),
    PokemonGen4.SHEDINJA: PokemonRelation(want={'grass'}, dont_want={'fire'}),
    PokemonGen4.SHELGON: PokemonRelation(),
    PokemonGen4.SHELLDER: PokemonRelation(dont_want={'water'}),
    PokemonGen4.SHELLOS: PokemonRelation(want={'water', 'fire'}, dont_want={'grass'}),
    PokemonGen4.SHIELDON: PokemonRelation(dont_want={'water', 'fire', 'grass'}),
    PokemonGen4.SHIFTRY: PokemonRelation(),
    PokemonGen4.SHINX: PokemonRelation(want={'water'}, no_way_jose={'grass'}),
    PokemonGen4.SHROOMISH: PokemonRelation(really_want={'water'}, want={'grass'}, dont_want={'fire'}),
    PokemonGen4.SHUCKLE: PokemonRelation(dont_want={'water'}),
    PokemonGen4.SHUPPET: PokemonRelation(dont_want={'water'}),
    PokemonGen4.SILCOON: PokemonRelation(really_want={'grass'}, dont_want={'water'}),
    PokemonGen4.SKARMORY: PokemonRelation(really_want={'grass'}, dont_want={'water'}),
    PokemonGen4.SKIPLOOM: PokemonRelation(),
    PokemonGen4.SKITTY: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.SKORUPI: PokemonRelation(want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.SKUNTANK: PokemonRelation(),
    PokemonGen4.SLAKING: PokemonRelation(),
    PokemonGen4.SLAKOTH: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.SLOWBRO: PokemonRelation(really_want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.SLOWKING: PokemonRelation(really_want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.SLOWPOKE: PokemonRelation(),
    PokemonGen4.SLUGMA: PokemonRelation(dont_want={'water'}),
    PokemonGen4.SMEARGLE: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.SMOOCHUM: PokemonRelation(want={'grass'}, dont_want={'water'}),
    PokemonGen4.SNEASEL: PokemonRelation(want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.SNORLAX: PokemonRelation(),
    PokemonGen4.SNORUNT: PokemonRelation(),
    PokemonGen4.SNOVER: PokemonRelation(really_want={'grass'}, dont_want={'fire'}),
    PokemonGen4.SNUBBULL: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.SOLROCK: PokemonRelation(really_want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.SPEAROW: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.SPHEAL: PokemonRelation(dont_want={'water'}),
    PokemonGen4.SPINARAK: PokemonRelation(want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.SPINDA: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.SPIRITOMB: PokemonRelation(dont_want={'water'}),
    PokemonGen4.SPOINK: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.SQUIRTLE: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.STANTLER: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.STARAPTOR: PokemonRelation(),
    PokemonGen4.STARAVIA: PokemonRelation(),
    PokemonGen4.STARLY: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.STARMIE: PokemonRelation(),
    PokemonGen4.STARYU: PokemonRelation(really_want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.STEELIX: PokemonRelation(),
    PokemonGen4.STUNKY: PokemonRelation(dont_want={'water', 'grass'}),
    PokemonGen4.SUDOWOODO: PokemonRelation(),
    PokemonGen4.SUICUNE: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.SUNFLORA: PokemonRelation(),
    PokemonGen4.SUNKERN: PokemonRelation(want={'grass'}, dont_want={'fire'}),
    PokemonGen4.SURSKIT: PokemonRelation(really_want={'grass'}, dont_want={'water'}),
    PokemonGen4.SWABLU: PokemonRelation(really_want={'fire', 'grass'}, dont_want={'water'}),
    PokemonGen4.SWALOT: PokemonRelation(),
    PokemonGen4.SWAMPERT: PokemonRelation(),
    PokemonGen4.SWELLOW: PokemonRelation(),
    PokemonGen4.SWINUB: PokemonRelation(),
    PokemonGen4.TAILLOW: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.TANGELA: PokemonRelation(want={'grass'}, dont_want={'fire'}),
    PokemonGen4.TANGROWTH: PokemonRelation(),
    PokemonGen4.TAUROS: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.TEDDIURSA: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.TENTACOOL: PokemonRelation(really_want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.TENTACRUEL: PokemonRelation(),
    PokemonGen4.TOGEKISS: PokemonRelation(),
    PokemonGen4.TOGEPI: PokemonRelation(really_want={'grass'}, want={'fire'}, dont_want={'water'}),
    PokemonGen4.TOGETIC: PokemonRelation(),
    PokemonGen4.TORCHIC: PokemonRelation(),
    PokemonGen4.TORKOAL: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.TORTERRA: PokemonRelation(),
    PokemonGen4.TOTODILE: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.TOXICROAK: PokemonRelation(),
    PokemonGen4.TRAPINCH: PokemonRelation(want={'water', 'fire'}),
    PokemonGen4.TREECKO: PokemonRelation(want={'grass'}, dont_want={'fire'}),
    PokemonGen4.TROPIUS: PokemonRelation(really_want={'grass'}),
    PokemonGen4.TURTWIG: PokemonRelation(),
    PokemonGen4.TYPHLOSION: PokemonRelation(),
    PokemonGen4.TYRANITAR: PokemonRelation(),
    PokemonGen4.TYROGUE: PokemonRelation(),
    PokemonGen4.UMBREON: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.UNOWN: PokemonRelation(dont_want={'water'}),
    PokemonGen4.URSARING: PokemonRelation(),
    PokemonGen4.UXIE: PokemonRelation(want={'fire'}, dont_want={'water'}),
    PokemonGen4.VAPOREON: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.VENOMOTH: PokemonRelation(),
    PokemonGen4.VENONAT: PokemonRelation(want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.VENUSAUR: PokemonRelation(),
    PokemonGen4.VESPIQUEN: PokemonRelation(),
    PokemonGen4.VIBRAVA: PokemonRelation(),
    PokemonGen4.VICTREEBEL: PokemonRelation(),
    PokemonGen4.VIGOROTH: PokemonRelation(),
    PokemonGen4.VILEPLUME: PokemonRelation(dont_want={'fire'}),
    PokemonGen4.VOLBEAT: PokemonRelation(really_want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.VOLTORB: PokemonRelation(want={'water'}, no_way_jose={'grass'}),
    PokemonGen4.VULPIX: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.WAILMER: PokemonRelation(want={'fire'}, dont_want={'water', 'grass'}),
    PokemonGen4.WAILORD: PokemonRelation(),
    PokemonGen4.WALREIN: PokemonRelation(),
    PokemonGen4.WARTORTLE: PokemonRelation(),
    PokemonGen4.WASH_ROTOM: PokemonRelation(really_want={'water'}, want={'fire'}, dont_want={'grass'}),
    PokemonGen4.WEAVILE: PokemonRelation(),
    PokemonGen4.WEEDLE: PokemonRelation(want={'grass'}, dont_want={'water', 'fire'}),
    PokemonGen4.WEEPINBELL: PokemonRelation(),
    PokemonGen4.WEEZING: PokemonRelation(),
    PokemonGen4.WHISCASH: PokemonRelation(),
    PokemonGen4.WHISMUR: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.WIGGLYTUFF: PokemonRelation(),
    PokemonGen4.WINGULL: PokemonRelation(really_want={'fire'}, want={'grass'}, dont_want={'water'}),
    PokemonGen4.WOBBUFFET: PokemonRelation(),
    PokemonGen4.WOOPER: PokemonRelation(want={'water', 'fire'}, dont_want={'grass'}),
    PokemonGen4.WORMADAM_PLANT: PokemonRelation(want={'grass'}, dont_want={'fire'}),
    PokemonGen4.WORMADAM_SANDY: PokemonRelation(),
    PokemonGen4.WORMADAM_TRASH: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.WURMPLE: PokemonRelation(),
    PokemonGen4.WYNAUT: PokemonRelation(),
    PokemonGen4.XATU: PokemonRelation(),
    PokemonGen4.YANMA: PokemonRelation(really_want={'grass'}, dont_want={'water'}),
    PokemonGen4.YANMEGA: PokemonRelation(),
    PokemonGen4.ZANGOOSE: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.ZAPDOS: PokemonRelation(really_want={'fire', 'grass'}, want={'water'}),
    PokemonGen4.ZIGZAGOON: PokemonRelation(dont_want={'water', 'fire'}),
    PokemonGen4.ZUBAT: PokemonRelation(really_want={'fire', 'grass'}, dont_want={'water'}),
}

