import re
from traceback import walk_tb
from app.models.pokemon_relation import PokemonRelation
from pokemendel_core.data.gen4 import PokemonGen4

STARTER_MAPPING: dict[str, PokemonRelation] = {
    PokemonGen4.ABRA: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.ABSOL: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.AERODACTYL: PokemonRelation(want={"fire", "grass"}, dont_want={"water"}),
    PokemonGen4.AIPOM: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.ANORITH: PokemonRelation(dont_want={"water"}),
    PokemonGen4.ARCEUS: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.ARON: PokemonRelation(dont_want={"water", "fire", "grass"}),
    PokemonGen4.ARTICUNO: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen4.AZELF: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.AZURILL: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.BAGON: PokemonRelation(want={"fire", "grass"}, dont_want={"water"}),
    PokemonGen4.BALTOY: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen4.BARBOACH: PokemonRelation(want={"fire", "water"}, dont_want={"grass"}),
    PokemonGen4.BELDUM: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen4.BELLOSSOM: PokemonRelation(dont_want={"fire"}),
    PokemonGen4.BELLSPROUT: PokemonRelation(dont_want={"fire"}),
    PokemonGen4.BIDOOF: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen4.BONSLY: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen4.BRONZOR: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen4.BUDEW: PokemonRelation(dont_want={"fire"}),
    PokemonGen4.BUIZEL: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen4.BULBASAUR: PokemonRelation(dont_want={"fire"}),
    PokemonGen4.BUNEARY: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.CACNEA: PokemonRelation(dont_want={"fire"}, want={"grass"}),
    PokemonGen4.CARNIVINE: PokemonRelation(dont_want={"fire"}),
    PokemonGen4.CASCOON: PokemonRelation(want={"grass"}, dont_want={"fire", "fire"}),
    PokemonGen4.CASTFORM: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen4.CATERPIE: PokemonRelation(want={"grass"}, dont_want={"water"}),
    PokemonGen4.CELEBI: PokemonRelation(want={"grass"}),
    PokemonGen4.CHARMANDER: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.CHATOT: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.CHERUBI: PokemonRelation(dont_want={"fire"}),
    PokemonGen4.CHIKORITA: PokemonRelation(dont_want={"fire"}),
    PokemonGen4.CHINCHOU: PokemonRelation(want={"fire", "water"}, dont_want={"grass"}),
    PokemonGen4.CHINGLING: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.CLEFFA: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.COMBEE: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen4.CORPHISH: PokemonRelation(dont_want={"grass"}),
    PokemonGen4.CORSOLA: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen4.CRANIDOS: PokemonRelation(dont_want={"water", "grass", "fire"}),
    PokemonGen4.CRESSELIA: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.CROAGUNK: PokemonRelation(want={"water"}, dont_want={"grass"}),
    PokemonGen4.CUBONE: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen4.CYNDAQUIL: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen4.DARKRAI: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.DELIBIRD: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen4.DEOXYS: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.DIALGA: PokemonRelation(dont_want={"fire"}),
    PokemonGen4.DIGLETT: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen4.DITTO: PokemonRelation(),
    PokemonGen4.DODUO: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.DRATINI: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.DRIFLOON: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.DROWZEE: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.DUNSPARCE: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.DUSKULL: PokemonRelation(dont_want={"water"}),
    PokemonGen4.EEVEE: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.EKANS: PokemonRelation(no_way_jose={"water"}, dont_want={"grass"}),
    PokemonGen4.ELECTRIKE: PokemonRelation(want={"water"}, no_way_jose={"grass"}),
    PokemonGen4.ELEKID: PokemonRelation(want={"water"}, no_way_jose={"grass"}),
    PokemonGen4.ENTEI: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.ESPEON: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.EXEGGCUTE: PokemonRelation(want={"grass"}),
    PokemonGen4.FAN_ROTOM: PokemonRelation(really_want={"grass"}, want={"fire", "water"}),
    PokemonGen4.FARFETCHD: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.FEEBAS: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen4.FINNEON: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen4.FLAREON: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.FROSLASS: PokemonRelation(dont_want={"water", "fire"}, really_want={"grass"}),
    PokemonGen4.FROST_ROTOM: PokemonRelation(really_want={"grass"}, want={"water"}, dont_want={"fire"}),
    PokemonGen4.GALLADE: PokemonRelation(want={"water", "fire"}),
    PokemonGen4.GARDEVOIR: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.GASTLY: PokemonRelation(dont_want={"water"}),
    PokemonGen4.GEODUDE: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen4.GIBLE: PokemonRelation(want={"fire", "water"}),
    PokemonGen4.GIRAFARIG: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.GIRATINA: PokemonRelation(dont_want={"water"}, want={"fire"}),
    PokemonGen4.GIRATINA: PokemonRelation(dont_want={"water"}, want={"fire"}),
    PokemonGen4.GLACEON: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen4.GLALIE: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen4.GLAMEOW: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen4.GLIGAR: PokemonRelation(want={"fire", "grass"}),
    PokemonGen4.GOLDEEN: PokemonRelation(dont_want={"grass", "water"}, want={"fire"}),
    PokemonGen4.GOREBYSS: PokemonRelation(dont_want={"grass", "water"}, want={"fire"}),
    PokemonGen4.GRIMER: PokemonRelation(dont_want={"grass"}, no_way_jose={"water"}),
    PokemonGen4.GROUDON: PokemonRelation(dont_want={"grass"}, want={"fire"}),
    PokemonGen4.GROWLITHE: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen4.GULPIN: PokemonRelation(dont_want={"grass"}, no_way_jose={"water"}),
    PokemonGen4.HAPPINY: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.HEAT_ROTOM: PokemonRelation(),
    PokemonGen4.HEATRAN: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen4.HERACROSS: PokemonRelation(really_want={"grass"}, want={"water"}, dont_want={"fire"}),
    PokemonGen4.HIPPOPOTAS: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen4.HITMONCHAN: PokemonRelation(want={"water"}),
    PokemonGen4.HITMONLEE: PokemonRelation(want={"water"}),
    PokemonGen4.HITMONTOP: PokemonRelation(want={"water"}),
    PokemonGen4.HO_OH: PokemonRelation(really_want={"grass", "fire"}, dont_want={"water"}),
    PokemonGen4.HOOTHOOT: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.HOPPIP: PokemonRelation(really_want={"grass"}),
    PokemonGen4.HORSEA: PokemonRelation(want={"fire"}),
    PokemonGen4.HOUNDOUR: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.HUNTAIL: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.IGGLYBUFF: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.ILLUMISE: PokemonRelation(really_want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen4.JIRACHI: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen4.JOLTEON: PokemonRelation(no_way_jose={"grass"}, want={"water"}),
    PokemonGen4.KABUTO: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen4.KANGASKHAN: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.KECLEON: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.KOFFING: PokemonRelation(no_way_jose={"water"}, dont_want={"grass"}),
    PokemonGen4.KRABBY: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.KRICKETOT: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen4.KYOGRE: PokemonRelation(dont_want={"grass", "water"}, want={"fire"}),
    PokemonGen4.LAPRAS: PokemonRelation(dont_want={"water"}),
    PokemonGen4.LARVITAR: PokemonRelation(dont_want={"fire", "water", "grass"}),
    PokemonGen4.LATIAS: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.LATIOS: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.LEAFEON: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen4.LEDYBA: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen4.LICKITUNG: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.LILEEP: PokemonRelation(dont_want={"grass", "fire"}),
    PokemonGen4.LOTAD: PokemonRelation(want={"fire"}),
    PokemonGen4.LUGIA: PokemonRelation(really_want={"fire", "grass"}, dont_want={"water"}),
    PokemonGen4.LUNATONE: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.LUVDISC: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.MACHOP: PokemonRelation(want={"water"}),
    PokemonGen4.MAGBY: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen4.MAGIKARP: PokemonRelation(really_want={"fire"}, want={"grass"}),
    PokemonGen4.MAGNEMITE: PokemonRelation(no_way_jose={"grass"}, want={"water"}, dont_want={"fire"}),
    PokemonGen4.MAKUHITA: PokemonRelation(want={"water"}),
    PokemonGen4.MANAPHY: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen4.MANKEY: PokemonRelation(want={"water"}),
    PokemonGen4.MANTYKE: PokemonRelation(really_want={"fire"}, want={"grass"}, dont_want={"water"}),
    PokemonGen4.MAREEP: PokemonRelation(no_way_jose={"grass"}, want={"water"}),
    PokemonGen4.MAWILE: PokemonRelation(dont_want={"water", "fire", "grass"}),
    PokemonGen4.MEDITITE: PokemonRelation(want={"fire", "water"}),
    PokemonGen4.MEOWTH: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.MESPRIT: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.MEW: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.MEWTWO: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.MILTANK: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.MIME_JR: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.MINUN: PokemonRelation(no_way_jose={"grass"}, want={"water"}),
    PokemonGen4.MISDREAVUS: PokemonRelation(dont_want={"water"}),
    PokemonGen4.MOLTRES: PokemonRelation(really_want={"grass", "fire"}, dont_want={"water"}),
    PokemonGen4.MOTHIM: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen4.MOW_ROTOM: PokemonRelation(dont_want={"grass", "fire"}, want={"water"}),
    PokemonGen4.MUDKIP: PokemonRelation(dont_want={"grass"}, want={"water", "fire"}),
    PokemonGen4.MUNCHLAX: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.MURKROW: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.NATU: PokemonRelation(really_want={"grass", "fire"}, dont_want={"water"}),
    PokemonGen4.NIDORAN_F: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen4.NIDORAN_M: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen4.NINJASK: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen4.NOSEPASS: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen4.NUMEL: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.OMANYTE: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen4.ONIX: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen4.PACHIRISU: PokemonRelation(no_way_jose={"grass"}, want={"water"}),
    PokemonGen4.PALKIA: PokemonRelation(want={"fire"}),
    PokemonGen4.PARAS: PokemonRelation(dont_want={"fire"}, want={"grass"}),
    PokemonGen4.PHANPY: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen4.PHIONE: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen4.PICHU: PokemonRelation(no_way_jose={"grass"}, want={"water"}),
    PokemonGen4.PIDGEY: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.PINECO: PokemonRelation(really_want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen4.PINSIR: PokemonRelation(really_want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen4.PLUSLE: PokemonRelation(no_way_jose={"grass"}, want={"water"}),
    PokemonGen4.POLITOED: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.POLIWRATH: PokemonRelation(want={"fire", "water"}, dont_want={"grass"}),
    PokemonGen4.PONYTA: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen4.POOCHYENA: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.PORYGON: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.PSYDUCK: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.QWILFISH: PokemonRelation(really_want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen4.RAIKOU: PokemonRelation(no_way_jose={"grass"}, want={"water"}),
    PokemonGen4.RATTATA: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.RAYQUAZA: PokemonRelation(really_want={"fire", "grass"}, want={"water"}),
    PokemonGen4.REGICE: PokemonRelation(dont_want={"fire", "water"}, want={"grass"}),
    PokemonGen4.REGIGIGAS: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen4.REGIROCK: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen4.REGISTEEL: PokemonRelation(dont_want={"water", "fire", "grass"}),
    PokemonGen4.RELICANTH: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen4.REMORAID: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen4.RHYHORN: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen4.RIOLU: PokemonRelation(want={"water"}, dont_want={"fire", "grass"}),
    PokemonGen4.ROTOM: PokemonRelation(want={"water"}),
    PokemonGen4.SABLEYE: PokemonRelation(dont_want={"water"}),
    PokemonGen4.SANDSHREW: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen4.SCYTHER: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen4.SEEDOT: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen4.SEEL: PokemonRelation(dont_want={"water"}),
    PokemonGen4.SENTRET: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.SEVIPER: PokemonRelation(no_way_jose={"water"}, dont_want={"grass"}),
    PokemonGen4.SHAYMIN_LAND: PokemonRelation(dont_want={"fire"}, want={"grass"}),
    PokemonGen4.SHAYMIN_SKY: PokemonRelation(really_want={"grass"}),
    PokemonGen4.SHEDINJA: PokemonRelation(dont_want={"fire"}, want={"grass"}),
    PokemonGen4.SHELLDER: PokemonRelation(dont_want={"water"}),
    PokemonGen4.SHELLOS: PokemonRelation(dont_want={"grass"}, want={"water", "fire"}),
    PokemonGen4.SHIELDON: PokemonRelation(dont_want={"water", "fire", "grass"}),
    PokemonGen4.SHINX: PokemonRelation(no_way_jose={"grass"}, want={"water"}),
    PokemonGen4.SHROOMISH: PokemonRelation(really_want=={"water"}, want={"grass"}, dont_want={"fire"}),
    PokemonGen4.SHUCKLE: PokemonRelation(dont_want={"water"}),
    PokemonGen4.SHUPPET: PokemonRelation(dont_want={"water"}),
    PokemonGen4.SILCOON: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen4.SKARMORY: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen4.SKITTY: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.SKORUPI: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen4.SLAKOTH: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.SLOWBRO: PokemonRelation(really_want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.SLOWKING: PokemonRelation(really_want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.SLUGMA: PokemonRelation(dont_want={"water"}),
    PokemonGen4.SMEARGLE: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.SMOOCHUM: PokemonRelation(want={"grass"}, dont_want={"water"}),
    PokemonGen4.SNEASEL: PokemonRelation(dont_want={"fire", "water"}, want={"grass"}),
    PokemonGen4.SNOVER: PokemonRelation(dont_want={"fire"}, really_want={"grass"}),
    PokemonGen4.SNUBBULL: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.SOLROCK: PokemonRelation(really_want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.SPEAROW: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.SPHEAL: PokemonRelation(dont_want={"water"}),
    PokemonGen4.SPINARAK: PokemonRelation(want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen4.SPINDA: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.SPIRITOMB: PokemonRelation(dont_want={"water"}),
    PokemonGen4.SPOINK: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.SQUIRTLE: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.STANTLER: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.STARLY: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.STARYU: PokemonRelation(really_want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.STUNKY: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen4.SUICUNE: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.SUNKERN: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen4.SURSKIT: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen4.SWABLU: PokemonRelation(really_want={"grass", "fire"}, dont_want={"water"}),
    PokemonGen4.SWINUB: PokemonRelation(),
    PokemonGen4.TAILLOW: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.TANGELA: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen4.TAUROS: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.TEDDIURSA: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.TENTACOOL: PokemonRelation(really_want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.TOGEPI: PokemonRelation(really_want={"grass"}, want={"fire"}, dont_want={"water"}),
    PokemonGen4.TORCHIC: PokemonRelation(),
    PokemonGen4.TORKOAL: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen4.TOTODILE: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.TRAPINCH: PokemonRelation(want={"fire", "water"}),
    PokemonGen4.TREECKO: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen4.TROPIUS: PokemonRelation(really_want={"grass"}),
    PokemonGen4.UMBREON: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.UNOWN: PokemonRelation(dont_want={"water"}),
    PokemonGen4.UXIE: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen4.VAPOREON: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.VENONAT: PokemonRelation(want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen4.VILEPLUME: PokemonRelation(dont_want={"fire"}),
    PokemonGen4.VOLBEAT: PokemonRelation(really_want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen4.VOLTORB: PokemonRelation(no_way_jose={"grass"}, want={"water"}),
    PokemonGen4.VULPIX: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.WAILMER: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen4.WASH_ROTOM: PokemonRelation(want={"fire"}, really_want={"water"}, dont_want={"grass"}),
    PokemonGen4.WEEDLE: PokemonRelation(want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen4.WHISMUR: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.WINGULL: PokemonRelation(want={"grass"}, really_want={"fire"}, dont_want={"water"}),
    PokemonGen4.WOOPER: PokemonRelation(want={"fire", "water"}, dont_want={"grass"}),
    PokemonGen4.WORMADAM_PLANT: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen4.WORMADAM_SANDY: PokemonRelation(),
    PokemonGen4.WORMADAM_TRASH: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.WYNAUT: PokemonRelation(),
    PokemonGen4.YANMA: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen4.ZANGOOSE: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.ZAPDOS: PokemonRelation(really_want={"grass", "fire"}, want={"water"}),
    PokemonGen4.ZIGZAGOON: PokemonRelation(dont_want={"fire", "water"}),
    PokemonGen4.ZUBAT: PokemonRelation(really_want={"grass", "fire"}, dont_want={"water"}),
}
