from selectors import PollSelector
from app.models.pokemon_relation import PokemonRelation
from pokemendel_core.data.gen3 import PokemonGen3

STARTER_MAPPING: dict[str, PokemonRelation] = {
    PokemonGen3.ABRA: PokemonRelation(want={"fire"}),
    PokemonGen3.AERODACTYL: PokemonRelation(want={"grass", "fire"}, dont_want={"water"}),
    PokemonGen3.AIPOM: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.ANORITH: PokemonRelation(want={"grass"}, dont_want={"water"}),
    PokemonGen3.ARON: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen3.ARTICUNO: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen3.AZURILL: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen3.BAGON: PokemonRelation(want={"fire", "grass"}),
    PokemonGen3.BALTOY: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen3.BARBOACH: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.BELDUM: PokemonRelation(dont_want={"water"}),
    PokemonGen3.BELLOSSOM: PokemonRelation(want={"water"}, dont_want={"fire", "grass"}),
    PokemonGen3.BELLSPROUT: PokemonRelation(want={"water", "grass"}, dont_want={"fire"}),
    PokemonGen3.BULBASAUR: PokemonRelation(want={"water", "grass"}, dont_want={"fire"}),
    PokemonGen3.CACNEA: PokemonRelation(want={"water"}, dont_want={"fire"}),
    PokemonGen3.CARVANHA: PokemonRelation(dont_want={"grass"}),
    PokemonGen3.CASCOON: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen3.CASTFORM: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.CATERPIE: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen3.CELEBI: PokemonRelation(want={"water"}),
    PokemonGen3.CHANSEY: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.CHARMANDER: PokemonRelation(want={"grass", "fire"}, dont_want={"water"}),
    PokemonGen3.CHIKORITA: PokemonRelation(want={"water"}, dont_want={"fire", "grass"}),
    PokemonGen3.CHIMECHO: PokemonRelation(want={"fire"}),
    PokemonGen3.CHINCHOU: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen3.CLEFFA: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.CORPHISH: PokemonRelation(dont_want={"grass"}),
    PokemonGen3.CORSOLA: PokemonRelation(dont_want={"grass"}),
    PokemonGen3.CUBONE: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen3.CYNDAQUIL: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen3.DELIBIRD: PokemonRelation(want={"grass"}),
    PokemonGen3.DEOXYS: PokemonRelation(want={"fire"}),
    PokemonGen3.DIGLETT: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen3.DITTO: PokemonRelation(),
    PokemonGen3.DODUO: PokemonRelation(really_want={"grass"}, want={"fire"}),
    PokemonGen3.DRATINI: PokemonRelation(really_want={"fire", "grass"}),
    PokemonGen3.DROWZEE: PokemonRelation(want={"fire"}),
    PokemonGen3.DUNSPARCE: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.DUSKULL: PokemonRelation(),
    PokemonGen3.EEVEE: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.EKANS: PokemonRelation(really_want={"grass"}),
    PokemonGen3.ELECTRIKE: PokemonRelation(no_way_jose={"water"}, dont_want={"grass"}),
    PokemonGen3.ELEKID: PokemonRelation(no_way_jose={"water"}, dont_want={"grass"}),
    PokemonGen3.ENTEI: PokemonRelation(want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen3.ESPEON: PokemonRelation(want={"fire"}),
    PokemonGen3.EXEGGCUTE: PokemonRelation(really_want={"water"}, want={"grass"}),
    PokemonGen3.FARFETCHD: PokemonRelation(really_want={"grass"}, want={"fire"}),
    PokemonGen3.FEEBAS: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.FLAREON: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen3.GASTLY: PokemonRelation(really_want={"grass"}),
    PokemonGen3.GEODUDE: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen3.GIRAFARIG: PokemonRelation(want={"fire"}),
    PokemonGen3.GLIGAR: PokemonRelation(want={"fire", "grass"}, dont_want={"water"}),
    PokemonGen3.GOLDEEN: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.GOREBYSS: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.GRIMER: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen3.GROUDON: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.GROWLITHE: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen3.GULPIN: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen3.HERACROSS: PokemonRelation(really_want={"grass"}, dont_want={"fire"}),
    PokemonGen3.HITMONCHAN: PokemonRelation(),
    PokemonGen3.HITMONLEE: PokemonRelation(),
    PokemonGen3.HITMONTOP: PokemonRelation(),
    PokemonGen3.HO_OH: PokemonRelation(really_want={"grass", "fire"}, dont_want={"water"}),
    PokemonGen3.HOOTHOOT: PokemonRelation(really_want={"grass"}, want={"fire"}),
    PokemonGen3.HOPPIP: PokemonRelation(really_want={"grass", "water"}),
    PokemonGen3.HORSEA: PokemonRelation(want={"fire"}),
    PokemonGen3.HOUNDOUR: PokemonRelation(really_want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen3.HUNTAIL: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.IGGLYBUFF: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.ILLUMISE: PokemonRelation(really_want={"grass"}, want={"fire"}),
    PokemonGen3.JIRACHI: PokemonRelation(want={"grass"}),
    PokemonGen3.JOLTEON: PokemonRelation(no_way_jose={"water"}, dont_want={"grass"}),
    PokemonGen3.KABUTO: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen3.KANGASKHAN: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.KECLEON: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.KOFFING: PokemonRelation(want={"grass"}, dont_want={"water"}),
    PokemonGen3.KRABBY: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.KYOGRE: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.LAPRAS: PokemonRelation(),
    PokemonGen3.LARVITAR: PokemonRelation(dont_want={"water", "grass", "fire"}),
    PokemonGen3.LATIAS: PokemonRelation(really_want={"fire", "grass"}),
    PokemonGen3.LATIOS: PokemonRelation(really_want={"fire", "grass"}),
    PokemonGen3.LEDYBA: PokemonRelation(really_want={"grass"}),
    PokemonGen3.LICKITUNG: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.LILEEP: PokemonRelation(dont_want={"water"}),
    PokemonGen3.LOTAD: PokemonRelation(really_want={"water"}, want={"fire"}, dont_want={"grass"}),
    PokemonGen3.LUGIA: PokemonRelation(really_want={"fire", "grass"}),
    PokemonGen3.LUNATONE: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen3.LUVDISC: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.MACHOP: PokemonRelation(),
    PokemonGen3.MAGBY: PokemonRelation(really_want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen3.MAGIKARP: PokemonRelation(really_want={"fire"}),
    PokemonGen3.MAGNEMITE: PokemonRelation(no_way_jose={"water"}, dont_want={"fire"}),
    PokemonGen3.MAKUHITA: PokemonRelation(),
    PokemonGen3.MANKEY: PokemonRelation(),
    PokemonGen3.MANTINE: PokemonRelation(really_want={"fire"}, want={"water"}),
    PokemonGen3.MAREEP: PokemonRelation(no_way_jose={"water"}, dont_want={"grass"}),
    PokemonGen3.MAWILE: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen3.MEDITITE: PokemonRelation(want={"fire"}),
    PokemonGen3.MEOWTH: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.MEW: PokemonRelation(want={"fire"}),
    PokemonGen3.MEWTWO: PokemonRelation(want={"fire"}),
    PokemonGen3.MILTANK: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.MINUN: PokemonRelation(no_way_jose={"water"}, dont_want={"grass"}),
    PokemonGen3.MISDREAVUS: PokemonRelation(),
    PokemonGen3.MOLTRES: PokemonRelation(really_want={"grass", "fire"}, dont_want={"water"}),
    PokemonGen3.MR_MIME: PokemonRelation(want={"fire"}),
    PokemonGen3.MURKROW: PokemonRelation(really_want={"grass"}, want={"fire"}),
    PokemonGen3.NATU: PokemonRelation(really_want={"grass"}, want={"fire"}),
    PokemonGen3.NIDORAN_F: PokemonRelation(want={"fire", "grass"}, dont_want={"water"}),
    PokemonGen3.NIDORAN_M: PokemonRelation(want={"fire", "grass"}, dont_want={"water"}),
    PokemonGen3.NINJASK: PokemonRelation(really_want={"grass"}),
    PokemonGen3.NOSEPASS: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen3.NUMEL: PokemonRelation(want={"fire", "grass"}, dont_want={"water"}),
    PokemonGen3.OMANYTE: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen3.ONIX: PokemonRelation(dont_want={"water"}),
    PokemonGen3.PARAS: PokemonRelation(really_want={"grass", "water"}, dont_want={"fire"}),
    PokemonGen3.PHANPY: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen3.PICHU: PokemonRelation(no_way_jose={"water"}, dont_want={"grass"}),
    PokemonGen3.PIDGEY: PokemonRelation(really_want={"grass"}, want={"fire"}),
    PokemonGen3.PINECO: PokemonRelation(really_want={"grass"}, dont_want={"fire"}),
    PokemonGen3.PINSIR: PokemonRelation(really_want={"grass"}, dont_want={"fire"}),
    PokemonGen3.PLUSLE: PokemonRelation(no_way_jose={"water"}, dont_want={"grass"}),
    PokemonGen3.POLITOED: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.POLIWRATH: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.PONYTA: PokemonRelation(really_want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen3.POOCHYENA: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.PORYGON: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.PSYDUCK: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.QWILFISH: PokemonRelation(really_want={"fire"}, want={"grass"}, dont_want={"water"}),
    PokemonGen3.RAIKOU: PokemonRelation(no_way_jose={"water"}, dont_want={"grass"}),
    PokemonGen3.RALTS: PokemonRelation(want={"fire"}),
    PokemonGen3.RATTATA: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.RAYQUAZA: PokemonRelation(really_want={"fire", "grass"}, want={"water"}),
    PokemonGen3.REGICE: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen3.REGIROCK: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen3.REGISTEEL: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen3.RELICANTH: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen3.REMORAID: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen3.RHYHORN: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen3.ROSELIA: PokemonRelation(really_want={"water", "grass"}, dont_want={"fire"}),
    PokemonGen3.SABLEYE: PokemonRelation(),
    PokemonGen3.SANDSHREW: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen3.SCYTHER: PokemonRelation(really_want={"grass"}, dont_want={"fire"}),
    PokemonGen3.SEEDOT: PokemonRelation(really_want={"water"}, want={"grass"}, dont_want={"fire"}),
    PokemonGen3.SEEL: PokemonRelation(),
    PokemonGen3.SENTRET: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.SEVIPER: PokemonRelation(really_want={"grass"}, dont_want={"water"}),
    PokemonGen3.SHEDINJA: PokemonRelation(really_want={"grass", "water"}, dont_want={"fire"}),
    PokemonGen3.SHELLDER: PokemonRelation(),
    PokemonGen3.SHROOMISH: PokemonRelation(really_want={"water"}, want={"grass"}, dont_want={"fire"}),
    PokemonGen3.SHUCKLE: PokemonRelation(want={"grass"}, dont_want={"water"}),
    PokemonGen3.SHUPPET: PokemonRelation(),
    PokemonGen3.SILCOON: PokemonRelation(really_want={"grass"}),
    PokemonGen3.SKARMORY: PokemonRelation(really_want={"grass"}),
    PokemonGen3.SKITTY: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.SLAKOTH: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.SLOWBRO: PokemonRelation(really_want={"fire"}, dont_want={"grass"}),
    PokemonGen3.SLOWKING: PokemonRelation(really_want={"fire"}, dont_want={"grass"}),
    PokemonGen3.SLUGMA: PokemonRelation(want={"grass"}, dont_want={"water"}),
    PokemonGen3.SMEARGLE: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.SMOOCHUM: PokemonRelation(want={"grass"}),
    PokemonGen3.SNEASEL: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen3.SNORLAX: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.SNORUNT: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen3.SNUBBULL: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.SOLROCK: PokemonRelation(dont_want={"water", "grass"}),
    PokemonGen3.SPEAROW: PokemonRelation(really_want={"grass"}, want={"fire"}),
    PokemonGen3.SPHEAL: PokemonRelation(),
    PokemonGen3.SPINARAK: PokemonRelation(really_want={"grass"}, dont_want={"fire"}),
    PokemonGen3.SPINDA: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.SPOINK: PokemonRelation(want={"fire"}),
    PokemonGen3.SQUIRTLE: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.STANTLER: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.STARYU: PokemonRelation(really_want={"fire"}, dont_want={"grass"}),
    PokemonGen3.SUDOWOODO: PokemonRelation(),
    PokemonGen3.SUICUNE: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.SUNKERN: PokemonRelation(want={"water"}, dont_want={"grass", "fire"}),
    PokemonGen3.SURSKIT: PokemonRelation(really_want={"grass"}),
    PokemonGen3.SWABLU: PokemonRelation(really_want={"grass"}, want={"fire"}),
    PokemonGen3.SWINUB: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen3.TAILLOW: PokemonRelation(really_want={"grass"}, want={"fire"}),
    PokemonGen3.TANGELA: PokemonRelation(really_want={"water"}, dont_want={"grass", "fire"}),
    PokemonGen3.TAUROS: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.TEDDIURSA: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.TENTACOOL: PokemonRelation(really_want={"fire"}, want={"grass"}, dont_want={"water"}),
    PokemonGen3.TOGEPI: PokemonRelation(really_want={"grass"}, want={"fire"}),
    PokemonGen3.TORKOAL: PokemonRelation(really_want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen3.TOTODILE: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.TRAPINCH: PokemonRelation(really_want={"fire"}, want={"grass", "water"}),
    PokemonGen3.TROPIUS: PokemonRelation(really_want={"grass", "water"}),
    PokemonGen3.UMBREON: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.UNOWN: PokemonRelation(),
    PokemonGen3.VAPOREON: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.VENONAT: PokemonRelation(really_want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen3.VILEPLUME: PokemonRelation(really_want={"grass", "water"}, dont_want={"fire"}),
    PokemonGen3.VOLBEAT: PokemonRelation(really_want={"grass"}, dont_want={"fire"}),
    PokemonGen3.VOLTORB: PokemonRelation(no_way_jose={"water"}, dont_want={"grass"}),
    PokemonGen3.VULPIX: PokemonRelation(want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen3.WAILMER: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.WEEDLE: PokemonRelation(really_want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen3.WHISMUR: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.WINGULL: PokemonRelation(really_want={"fire"}, want={"water", "grass"}),
    PokemonGen3.WOOPER: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen3.WYNAUT: PokemonRelation(),
    PokemonGen3.YANMA: PokemonRelation(really_want={"grass"}),
    PokemonGen3.ZANGOOSE: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.ZAPDOS: PokemonRelation(really_want={"grass"}, want={"fire"}),
    PokemonGen3.ZIGZAGOON: PokemonRelation(dont_want={"fire"}),
    PokemonGen3.ZUBAT: PokemonRelation(really_want={"grass"}, want={"fire"}),
}
