from app.models.pokemon_relation import PokemonRelation
from pokemendel_core.data.gen2 import PokemonGen2

STARTER_MAPPING: dict[str, PokemonRelation] = {
    PokemonGen2.ABRA: PokemonRelation(),
    PokemonGen2.AERODACTYL: PokemonRelation(dont_want={"water"}),
    PokemonGen2.AIPOM: PokemonRelation(),
    PokemonGen2.ARTICUNO: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.BELLOSSOM: PokemonRelation(want={"water"}, dont_want={"fire", "grass"}),
    PokemonGen2.BELLSPROUT: PokemonRelation(want={"water"}, dont_want={"fire"}),
    PokemonGen2.BULBASAUR: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.CATERPIE: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.CELEBI: PokemonRelation(want={"water"}, dont_want={"fire"}),
    PokemonGen2.CHANSEY: PokemonRelation(),
    PokemonGen2.CHARMANDER: PokemonRelation(want={"grass"}, dont_want={"water"}),
    PokemonGen2.CHINCHOU: PokemonRelation(want={"water", "fire"}, dont_want={"grass"}),
    PokemonGen2.CLEFFA: PokemonRelation(),
    PokemonGen2.CORSOLA: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen2.CUBONE: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.DELIBIRD: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.DIGLETT: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.DITTO: PokemonRelation(),
    PokemonGen2.DODUO: PokemonRelation(want={"grass"}),
    PokemonGen2.DRATINI: PokemonRelation(want={"grass"}),
    PokemonGen2.DROWZEE: PokemonRelation(),
    PokemonGen2.DUNSPARCE: PokemonRelation(),
    PokemonGen2.EEVEE: PokemonRelation(),
    PokemonGen2.EKANS: PokemonRelation(want={"grass"}),
    PokemonGen2.ELEKID: PokemonRelation(want={"water"}, dont_want={"grass"}),
    PokemonGen2.ENTEI: PokemonRelation(want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen2.ESPEON: PokemonRelation(),
    PokemonGen2.EXEGGCUTE: PokemonRelation(want={"water"}, dont_want={"fire"}),
    PokemonGen2.FARFETCHD: PokemonRelation(want={"grass"}),
    PokemonGen2.FLAREON: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen2.GASTLY: PokemonRelation(want={"grass"}),
    PokemonGen2.GEODUDE: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.GIRAFARIG: PokemonRelation(),
    PokemonGen2.GLIGAR: PokemonRelation(want={"fire"}, dont_want={"water"}),
    PokemonGen2.GOLDEEN: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.GRIMER: PokemonRelation(want={"grass"}),
    PokemonGen2.GROWLITHE: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen2.HERACROSS: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.HITMONCHAN: PokemonRelation(),
    PokemonGen2.HITMONLEE: PokemonRelation(),
    PokemonGen2.HITMONTOP: PokemonRelation(),
    PokemonGen2.HO_OH: PokemonRelation(want={"grass"}, dont_want={"water"}),
    PokemonGen2.HOOTHOOT: PokemonRelation(want={"grass"}),
    PokemonGen2.HOPPIP: PokemonRelation(want={"water", "grass"}, dont_want={"fire"}),
    PokemonGen2.HORSEA: PokemonRelation(want={"fire"}),
    PokemonGen2.HOUNDOUR: PokemonRelation(want={"grass"}, dont_want={"water"}),
    PokemonGen2.IGGLYBUFF: PokemonRelation(),
    PokemonGen2.JOLTEON: PokemonRelation(want={"water"}, dont_want={"grass"}),
    PokemonGen2.KABUTO: PokemonRelation(want={"fire"}, dont_want={"green"}),
    PokemonGen2.KANGASKHAN: PokemonRelation(),
    PokemonGen2.KOFFING: PokemonRelation(want={"grass"}),
    PokemonGen2.KRABBY: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen2.LAPRAS: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen2.LARVITAR: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.LEDYBA: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.LICKITUNG: PokemonRelation(),
    PokemonGen2.LUGIA: PokemonRelation(want={"grass"}),
    PokemonGen2.MACHOP: PokemonRelation(),
    PokemonGen2.MAGBY: PokemonRelation(want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen2.MAGIKARP: PokemonRelation(want={"fire"}),
    PokemonGen2.MAGNEMITE: PokemonRelation(want={"water"}, dont_want={"grass", "fire"}),
    PokemonGen2.MANKEY: PokemonRelation(),
    PokemonGen2.MANTINE: PokemonRelation(want={"fire"}),
    PokemonGen2.MAREEP: PokemonRelation(want={"water"}, dont_want={"grass"}),
    PokemonGen2.MARILL: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.MEOWTH: PokemonRelation(),
    PokemonGen2.MEW: PokemonRelation(),
    PokemonGen2.MEWTWO: PokemonRelation(),
    PokemonGen2.MILTANK: PokemonRelation(),
    PokemonGen2.MISDREAVUS: PokemonRelation(),
    PokemonGen2.MOLTRES: PokemonRelation(want={"grass"}, dont_want={"water"}),
    PokemonGen2.MR_MIME: PokemonRelation(),
    PokemonGen2.MURKROW: PokemonRelation(want={"grass"}),
    PokemonGen2.NATU: PokemonRelation(want={"grass"}),
    PokemonGen2.NIDORAN_F: PokemonRelation(want={"fire", "grass"}, dont_want={"water"}),
    PokemonGen2.NIDORAN_M: PokemonRelation(want={"fire", "grass"}, dont_want={"water"}),
    PokemonGen2.OMANYTE: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen2.STEELIX: PokemonRelation(dont_want={"water", "fire"}),
    PokemonGen2.PARAS: PokemonRelation(want={"grass", "water"}, dont_want={"fire"}),
    PokemonGen2.PHANPY: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.PICHU: PokemonRelation(want={"water"}, dont_want={"grass"}),
    PokemonGen2.PIDGEY: PokemonRelation(want={"grass"}),
    PokemonGen2.PINECO: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.PINSIR: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.POLITOED: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.POLIWRATH: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen2.PONYTA: PokemonRelation(want={"grass"}, dont_want={"water", "fire"}),
    PokemonGen2.PORYGON: PokemonRelation(),
    PokemonGen2.PSYDUCK: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.QWILFISH: PokemonRelation(want={"fire"}),
    PokemonGen2.RAIKOU: PokemonRelation(want={"water"}, dont_want={"grass"}),
    PokemonGen2.RATTATA: PokemonRelation(),
    PokemonGen2.REMORAID: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.RHYHORN: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.SANDSHREW: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.SCYTHER: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.SEEL: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen2.SENTRET: PokemonRelation(),
    PokemonGen2.SHELLDER: PokemonRelation(dont_want={"grass", "water"}),
    PokemonGen2.SHUCKLE: PokemonRelation(dont_want={"water"}),
    PokemonGen2.SKARMORY: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.SLOWBRO: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen2.SLOWKING: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen2.SLUGMA: PokemonRelation(want={"fire", "grass"}, dont_want={"water"}),
    PokemonGen2.SMEARGLE: PokemonRelation(),
    PokemonGen2.SMOOCHUM: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.SNEASEL: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.SNORLAX: PokemonRelation(),
    PokemonGen2.SNUBBULL: PokemonRelation(),
    PokemonGen2.SPEAROW: PokemonRelation(want={"grass"}),
    PokemonGen2.SPINARAK: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.SQUIRTLE: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen2.STANTLER: PokemonRelation(),
    PokemonGen2.STARYU: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen2.SUDOWOODO: PokemonRelation(want={"fire"}, dont_want={"water", "grass"}),
    PokemonGen2.SUICUNE: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen2.SUNKERN: PokemonRelation(want={"water"}, dont_want={"grass", "fire"}),
    PokemonGen2.SWINUB: PokemonRelation(dont_want={"water"}),
    PokemonGen2.TANGELA: PokemonRelation(want={"water"}, dont_want={"grass", "fire"}),
    PokemonGen2.TAUROS: PokemonRelation(),
    PokemonGen2.TEDDIURSA: PokemonRelation(),
    PokemonGen2.TENTACOOL: PokemonRelation(want={"fire", "grass"}),
    PokemonGen2.TOGEPI: PokemonRelation(want={"grass"}),
    PokemonGen2.UMBREON: PokemonRelation(),
    PokemonGen2.UNOWN: PokemonRelation(),
    PokemonGen2.VAPOREON: PokemonRelation(want={"fire"}, dont_want={"grass", "water"}),
    PokemonGen2.VENONAT: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.VILEPLUME: PokemonRelation(want={"water", "grass"}, dont_want={"fire"}),
    PokemonGen2.VOLTORB: PokemonRelation(want={"water"}, dont_want={"grass"}),
    PokemonGen2.VULPIX: PokemonRelation(want={"grass"}, dont_want={"fire", "water"}),
    PokemonGen2.WEEDLE: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.WOBBUFFET: PokemonRelation(),
    PokemonGen2.WOOPER: PokemonRelation(want={"fire"}, dont_want={"grass"}),
    PokemonGen2.YANMA: PokemonRelation(want={"grass"}, dont_want={"fire"}),
    PokemonGen2.ZAPDOS: PokemonRelation(want={"grass", "water"}),
    PokemonGen2.ZUBAT: PokemonRelation(want={"grass"}),
}
